// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqqYjftlpP_iqhTwJ3gfLueCAU14AR1xs',
    appId: '1:83345835774:web:08760cd1738c9da60d47af',
    messagingSenderId: '83345835774',
    projectId: 'quraanapp-5312e',
    authDomain: 'quraanapp-5312e.firebaseapp.com',
    storageBucket: 'quraanapp-5312e.firebasestorage.app',
    measurementId: 'G-3EPPDTFTQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANV9XTIUo9VWw3DBgrZ5X7TF-qcyH5X4Q',
    appId: '1:83345835774:android:03a02a4a6ebe81860d47af',
    messagingSenderId: '83345835774',
    projectId: 'quraanapp-5312e',
    storageBucket: 'quraanapp-5312e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQtFUSKeireY6OKT7bcJ10HywHVP9F-gY',
    appId: '1:83345835774:ios:e24a4e0856d938800d47af',
    messagingSenderId: '83345835774',
    projectId: 'quraanapp-5312e',
    storageBucket: 'quraanapp-5312e.firebasestorage.app',
    iosBundleId: 'com.example.quraanapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQtFUSKeireY6OKT7bcJ10HywHVP9F-gY',
    appId: '1:83345835774:ios:e24a4e0856d938800d47af',
    messagingSenderId: '83345835774',
    projectId: 'quraanapp-5312e',
    storageBucket: 'quraanapp-5312e.firebasestorage.app',
    iosBundleId: 'com.example.quraanapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqqYjftlpP_iqhTwJ3gfLueCAU14AR1xs',
    appId: '1:83345835774:web:d7f0e060a5c8ec910d47af',
    messagingSenderId: '83345835774',
    projectId: 'quraanapp-5312e',
    authDomain: 'quraanapp-5312e.firebaseapp.com',
    storageBucket: 'quraanapp-5312e.firebasestorage.app',
    measurementId: 'G-DTNYJ14BVY',
  );
}
